export type Inventor = {
  profile: number; year: string; name: string; slug: string;
  descriptor?: string; contribution?: string; field?: string; status?: string; place?: string; note?: string;
};

export const inventors: Inventor[] = [
  {"profile": 1, "year": "1753", "name": "Benjamin Banneker", "slug": "benjamin-banneker", "descriptor": "Clockmaker, astronomer and almanac author before the federal patent era", "contribution": "Construction of a wooden striking clock after close study of an existing timepiece.", "field": "Mechanics, astronomy, surveying", "status": "Documented technical achievement; no U.S. patent", "place": "Baltimore County, Maryland", "note": "The manuscript explicitly distinguishes Banneker’s sophisticated workmanship from the inaccurate claim that he “invented the clock.”"},
  {"profile": 2, "year": "c. 1800s", "name": "James Forten", "slug": "james-forten", "descriptor": "A sailmaker credited with a practical sail-handling improvement", "contribution": "An apparatus or practical improvement for managing sails in early American shipping.", "field": "Sailmaking and maritime technology", "status": "No known patent; credited in Henry E. Baker’s historical account", "place": "Philadelphia, Pennsylvania", "note": "No surviving technical specification establishes the exact mechanism; the manuscript presents Forten as a documented innovator outside the patent system."},
  {"profile": 3, "year": "1824", "name": "Robert Benjamin Lewis", "slug": "robert-benjamin-lewis", "descriptor": "An early serial patentee working across practical tools and fiber processing", "contribution": "A machine for dressing flax and hemp, followed by later patents involving oakum and hair, feathers, and brushes.", "field": "Mechanical processing and practical tools", "status": "1824 patent; later patents documented in 1836, 1840, and 1841", "place": "Maine", "note": "The manuscript notes that the pre-1836 record is incomplete while later patents provide stronger technical detail."},
  {"profile": 4, "year": "1834", "name": "Henry Blair", "slug": "henry-blair", "descriptor": "Patentee of coordinated seed- and cotton-planting machinery", "contribution": "A horse-drawn seed planter and a later cotton planter coordinating soil preparation, seed delivery, and covering.", "field": "Agricultural machinery", "status": "1834 Seed-Planter, Patent 8447X; 1836 Cotton-Planter, U.S. Patent No. 15", "place": "United States", "note": "The manuscript emphasizes the unusual archival significance of a Patent Office digest explicitly identifying Blair as “colored.”"},
  {"profile": 5, "year": "1843", "name": "Norbert Rillieux", "slug": "norbert-rillieux", "descriptor": "Engineer of a major advance in industrial sugar processing", "contribution": "Multiple-effect evaporation for more efficient sugar refining.", "field": "Chemical and mechanical engineering", "status": "U.S. Patent No. 3,237 (1843)", "place": "Louisiana", "note": "Presented in the manuscript as a decisive advance in industrial sugar processing."},
  {"profile": 6, "year": "1845", "name": "Joseph Hawkins", "slug": "joseph-hawkins", "descriptor": "Inventor associated with improved cooking and household equipment", "contribution": "A gridiron designed to improve control while broiling food.", "field": "Household and cooking technology", "status": "Profile documented in the manuscript chronology", "place": "United States", "note": "Full archival detail remains in the manuscript profile."},
  {"profile": 7, "year": "1848", "name": "Lewis Temple", "slug": "lewis-temple", "descriptor": "A Blacksmith whose toggle harpoon changed nineteenth-century whaling", "contribution": "A toggle harpoon designed to hold more securely after entering a whale.", "field": "Maritime technology", "status": "Documented technical contribution; not patented by Temple", "place": "New Bedford, Massachusetts", "note": "The manuscript preserves the distinction between Temple’s documented design and the patent record."},
  {"profile": 8, "year": "1867", "name": "Henry Lee", "slug": "henry-lee"},
  {"profile": 9, "year": "1867", "name": "William A. Deitz", "slug": "william-a-deitz"},
  {"profile": 10, "year": "1870", "name": "Thomas Elkins", "slug": "thomas-elkins"},
  {"profile": 11, "year": "1870", "name": "Turner Byrd Jr", "slug": "turner-byrd-jr"},
  {"profile": 12, "year": "1870", "name": "Harde Spears", "slug": "harde-spears"},
  {"profile": 13, "year": "1871", "name": "Landrow Bell", "slug": "landrow-bell"},
  {"profile": 14, "year": "1872", "name": "Thomas J. Martin", "slug": "thomas-j-martin"},
  {"profile": 15, "year": "1872", "name": "Elijah McCoy", "slug": "elijah-mccoy"},
  {"profile": 16, "year": "1873", "name": "Mary Jones De Leon", "slug": "mary-jones-de-leon"},
  {"profile": 17, "year": "1874", "name": "Lewis H. Latimer", "slug": "lewis-h-latimer"},
  {"profile": 18, "year": "1874", "name": "Edward H. Sutton", "slug": "edward-h-sutton"},
  {"profile": 19, "year": "1874", "name": "Henry Pickett", "slug": "henry-pickett"},
  {"profile": 20, "year": "1875", "name": "David A. Fisher Jr", "slug": "david-a-fisher-jr"},
  {"profile": 21, "year": "1875", "name": "Alexander P. Ashbourne", "slug": "alexander-p-ashbourne"},
  {"profile": 22, "year": "1876", "name": "Thomas A. Carrington", "slug": "thomas-a-carrington"},
  {"profile": 23, "year": "1878", "name": "Benjamin H. Taylor", "slug": "benjamin-h-taylor"},
  {"profile": 24, "year": "1878", "name": "Joseph R. Winters", "slug": "joseph-r-winters"},
  {"profile": 25, "year": "1878", "name": "William A. Lavalette", "slug": "william-a-lavalette"},
  {"profile": 26, "year": "1878", "name": "William R. Davis Jr", "slug": "william-r-davis-jr"},
  {"profile": 27, "year": "1878", "name": "Osbourn Dorsey", "slug": "osbourn-dorsey"},
  {"profile": 28, "year": "1879", "name": "M. William Binga", "slug": "m-william-binga"},
  {"profile": 29, "year": "1879", "name": "William Bailis", "slug": "william-bailis"},
  {"profile": 30, "year": "1880", "name": "Joseph W. Waller", "slug": "joseph-w-waller"},
  {"profile": 31, "year": "1883", "name": "Jan Ernst Matzeliger", "slug": "jan-ernst-matzeliger"},
  {"profile": 32, "year": "1884", "name": "Judy W. Reed", "slug": "judy-w-reed"},
  {"profile": 33, "year": "1884", "name": "Granville T. Woods", "slug": "granville-t-woods"},
  {"profile": 34, "year": "1885", "name": "Sarah E. Goode", "slug": "sarah-e-goode"},
  {"profile": 35, "year": "1886", "name": "Robert F. Flemming Jr", "slug": "robert-f-flemming-jr"},
  {"profile": 36, "year": "1967", "name": "James McCoy Jr", "slug": "james-mccoy-jr"},
  {"profile": 37, "year": "1888", "name": "Miriam E. Benjamin", "slug": "miriam-e-benjamin"},
  {"profile": 38, "year": "1888", "name": "Ellen Eglin", "slug": "ellen-eglin"},
  {"profile": 39, "year": "1892", "name": "Anna M. Mangin", "slug": "anna-m-mangin"},
  {"profile": 40, "year": "1892", "name": "Sarah Boone", "slug": "sarah-boone"},
  {"profile": 41, "year": "1894", "name": "George Washington Murray", "slug": "george-washington-murray"},
  {"profile": 42, "year": "1894", "name": "Joseph Lee", "slug": "joseph-lee"},
  {"profile": 43, "year": "1897", "name": "Alfred L. Cralle", "slug": "alfred-l-cralle"},
  {"profile": 44, "year": "1897", "name": "Andrew Jackson Beard", "slug": "andrew-jackson-beard"},
  {"profile": 45, "year": "1897", "name": "John Lee Love", "slug": "john-lee-love"},
  {"profile": 46, "year": "1898", "name": "Lyda D. Newman", "slug": "lyda-d-newman"},
  {"profile": 47, "year": "1899", "name": "John Albert Burr", "slug": "john-albert-burr"},
  {"profile": 48, "year": "1899", "name": "George Franklin Grant", "slug": "george-franklin-grant"},
  {"profile": 49, "year": "1906", "name": "Madam C. J. Walker", "slug": "madam-c-j-walker"},
  {"profile": 50, "year": "1914", "name": "Garrett A. Morgan", "slug": "garrett-a-morgan"},
  {"profile": 51, "year": "1919", "name": "Alice H. Parker", "slug": "alice-h-parker"},
  {"profile": 52, "year": "1928", "name": "Marjorie Stewart Joyner", "slug": "marjorie-stewart-joyner"},
  {"profile": 53, "year": "1951", "name": "Bessie Blount Griffin", "slug": "bessie-blount-griffin"},
  {"profile": 54, "year": "1952", "name": "Christina M. Jenkins", "slug": "christina-m-jenkins"},
  {"profile": 55, "year": "1956", "name": "Mary Beatrice Davidson Kenner", "slug": "mary-beatrice-davidson-kenner"},
  {"profile": 56, "year": "1962", "name": "James E. West", "slug": "james-e-west"},
  {"profile": 57, "year": "1969", "name": "Marie Van Brittan Brown", "slug": "marie-van-brittan-brown"},
  {"profile": 58, "year": "1976", "name": "Jerry Lawson", "slug": "jerry-lawson"},
  {"profile": 59, "year": "1980", "name": "Valerie L. Thomas", "slug": "valerie-l-thomas"},
  {"profile": 60, "year": "1988", "name": "Patricia E. Bath", "slug": "patricia-e-bath"},
  {"profile": 61, "year": "1990", "name": "Lonnie G. Johnson", "slug": "lonnie-g-johnson"},
  {"profile": 62, "year": "1997", "name": "Patricia S. Cowings", "slug": "patricia-s-cowings"},
  {"profile": 63, "year": "1998", "name": "Mark E. Dean", "slug": "mark-e-dean"},
  {"profile": 64, "year": "1999", "name": "Tahira Reid Smith", "slug": "tahira-reid-smith"},
  {"profile": 65, "year": "2000", "name": "Alexa I. Canady", "slug": "alexa-i-canady"},
  {"profile": 66, "year": "2003", "name": "Juan E. Gilbert", "slug": "juan-e-gilbert"},
  {"profile": 67, "year": "2006", "name": "Janet Emerson Bashen", "slug": "janet-emerson-bashen"},
  {"profile": 68, "year": "2007", "name": "Paula T. Hammond", "slug": "paula-t-hammond"},
  {"profile": 69, "year": "2008", "name": "Jessica O. Matthews", "slug": "jessica-o-matthews"},
  {"profile": 70, "year": "2009", "name": "Marian R. Croak", "slug": "marian-r-croak"},
  {"profile": 71, "year": "2010", "name": "Treena Livingston Arinzeh", "slug": "treena-livingston-arinzeh"},
  {"profile": 72, "year": "2013", "name": "Omowunmi A. Sadik", "slug": "omowunmi-a-sadik"},
  {"profile": 73, "year": "2015", "name": "Arlyne Simon", "slug": "arlyne-simon"},
  {"profile": 74, "year": "2015", "name": "Ayanna Howard", "slug": "ayanna-howard"},
  {"profile": 75, "year": "2017", "name": "Hadiyah-Nicole Green", "slug": "hadiyah-nicole-green"},
  {"profile": 76, "year": "2018", "name": "Aprille J. Ericsson", "slug": "aprille-j-ericsson"},
  {"profile": 77, "year": "2019", "name": "Lisa Dyson", "slug": "lisa-dyson"},
  {"profile": 78, "year": "2020", "name": "Kizzmekia S. Corbett-Helaire", "slug": "kizzmekia-s-corbett-helaire"},
  {"profile": 79, "year": "2021", "name": "Dasia Taylor", "slug": "dasia-taylor"},
  {"profile": 80, "year": "2024", "name": "Lanny Smoot", "slug": "lanny-smoot"},
  {"profile": 81, "year": "1929", "name": "David N. Crosthwait Jr", "slug": "david-n-crosthwait-jr"},
  {"profile": 82, "year": "1932", "name": "Lloyd Augustus Hall", "slug": "lloyd-augustus-hall"},
  {"profile": 83, "year": "1935", "name": "Percy Lavon Julian", "slug": "percy-lavon-julian"},
  {"profile": 84, "year": "1940", "name": "Frederick McKinley Jones", "slug": "frederick-mckinley-jones"},
  {"profile": 85, "year": "1956", "name": "Walter Lincoln Hawkins", "slug": "walter-lincoln-hawkins"},
  {"profile": 86, "year": "1959", "name": "Otis Frank Boykin", "slug": "otis-frank-boykin"},
  {"profile": 87, "year": "1960s", "name": "Annie J. Easley", "slug": "annie-j-easley"},
  {"profile": 88, "year": "1969", "name": "George R. Carruthers", "slug": "george-r-carruthers"},
  {"profile": 89, "year": "1971", "name": "Meredith C. Gourdine", "slug": "meredith-c-gourdine"},
  {"profile": 90, "year": "1971", "name": "Raye Jean Montague", "slug": "raye-jean-montague"},
  {"profile": 91, "year": "1973", "name": "Emmett W. Chappelle", "slug": "emmett-w-chappelle"},
  {"profile": 92, "year": "1975", "name": "Christine M. Darden", "slug": "christine-m-darden"},
  {"profile": 93, "year": "1980s", "name": "Gladys Mae West", "slug": "gladys-mae-west"},
  {"profile": 94, "year": "1985", "name": "Bettye Washington Greene", "slug": "bettye-washington-greene"},
  {"profile": 95, "year": "1986", "name": "Betty Wright Harris", "slug": "betty-wright-harris"},
  {"profile": 96, "year": "1987", "name": "Thomas O. Mensah", "slug": "thomas-o-mensah"},
  {"profile": 97, "year": "1990s", "name": "Lisa Gelobter", "slug": "lisa-gelobter"},
  {"profile": 98, "year": "2001", "name": "Sossina M. Haile", "slug": "sossina-m-haile"},
  {"profile": 99, "year": "2007", "name": "James McLurkin", "slug": "james-mclurkin"},
  {"profile": 100, "year": "2008", "name": "Warren M. Shadd", "slug": "warren-m-shadd"},
  {"profile": 101, "year": "1858", "name": "Benjamin T. Montgomery", "slug": "benjamin-t-montgomery"},
  {"profile": 102, "year": "1859", "name": "Benjamin Boardley", "slug": "benjamin-boardley"},
  {"profile": 103, "year": "1868", "name": "Martha Jones", "slug": "martha-jones"},
  {"profile": 104, "year": "1868", "name": "Samuel R. Scottron", "slug": "samuel-r-scottron"},
  {"profile": 105, "year": "1886", "name": "Henry Brown", "slug": "henry-brown"},
  {"profile": 106, "year": "1889", "name": "William H. Richardson", "slug": "william-h-richardson"},
  {"profile": 107, "year": "1890", "name": "William B. Purvis", "slug": "william-b-purvis"},
  {"profile": 108, "year": "1891", "name": "Philip B. Downing", "slug": "philip-b-downing"},
  {"profile": 109, "year": "1891", "name": "John Stanard", "slug": "john-stanard"},
  {"profile": 110, "year": "1895", "name": "Clatonia Joaquin Dorticus", "slug": "clatonia-joaquin-dorticus"},
  {"profile": 111, "year": "1896", "name": "Charles B. Brooks", "slug": "charles-b-brooks"},
  {"profile": 112, "year": "1900s", "name": "Annie Turnbo Malone", "slug": "annie-turnbo-malone"},
  {"profile": 113, "year": "1915", "name": "Alice Augusta Ball", "slug": "alice-augusta-ball"},
  {"profile": 114, "year": "1916", "name": "Madeline M. Turner", "slug": "madeline-m-turner"},
  {"profile": 115, "year": "1932", "name": "Richard B. Spikes", "slug": "richard-b-spikes"},
  {"profile": 116, "year": "1940s", "name": "Lucille Elizabeth Bishop Smith", "slug": "lucille-elizabeth-bishop-smith"},
  {"profile": 117, "year": "1971", "name": "Henry T. Sampson", "slug": "henry-t-sampson"},
  {"profile": 118, "year": "1972", "name": "Frank S. Greene Jr", "slug": "frank-s-greene-jr"},
  {"profile": 119, "year": "1984", "name": "George Edward Alcorn Jr", "slug": "george-edward-alcorn-jr"},
  {"profile": 120, "year": "1992", "name": "Jesse Eugene Russell", "slug": "jesse-eugene-russell"},
  {"profile": 121, "year": "1993", "name": "Robert G. Bryant", "slug": "robert-g-bryant"},
  {"profile": 122, "year": "1994", "name": "Tanya R. Allen", "slug": "tanya-r-allen"},
  {"profile": 123, "year": "1995", "name": "Donna M. Auguste", "slug": "donna-m-auguste"},
  {"profile": 124, "year": "1997", "name": "Cato T. Laurencin", "slug": "cato-t-laurencin"},
  {"profile": 125, "year": "1998", "name": "Sandra Johnson Baylor", "slug": "sandra-johnson-baylor"},
  {"profile": 126, "year": "2003", "name": "Joycelyn S. Harrison", "slug": "joycelyn-s-harrison"},
  {"profile": 127, "year": "2003", "name": "Hakeem M. Oluseyi", "slug": "hakeem-m-oluseyi"},
  {"profile": 128, "year": "2004", "name": "Onassis Matthews", "slug": "onassis-matthews"},
  {"profile": 129, "year": "2004", "name": "Mae C. Jemison", "slug": "mae-c-jemison"},
  {"profile": 130, "year": "2005", "name": "Stanley E. Woodard", "slug": "stanley-e-woodard"},
  {"profile": 131, "year": "2005", "name": "Garthen Leslie", "slug": "garthen-leslie"},
  {"profile": 132, "year": "2006", "name": "Elijah Abron", "slug": "elijah-abron"},
  {"profile": 133, "year": "2011", "name": "John O. Dabiri", "slug": "john-o-dabiri"},
  {"profile": 134, "year": "2018", "name": "Bishop B. Curry V", "slug": "bishop-b-curry-v"},
  {"profile": 135, "year": "2019", "name": "Lisa Ascolese", "slug": "lisa-ascolese"},
  {"profile": 136, "year": "2021", "name": "Rose Coppee", "slug": "rose-coppee"},
  {"profile": 137, "year": "2021", "name": "Asegun Henry", "slug": "asegun-henry"},
  {"profile": 138, "year": "2023", "name": "Heman Bekele", "slug": "heman-bekele"},
  {"profile": 139, "year": "2024", "name": "Monique Dyers", "slug": "monique-dyers"},
  {"profile": 140, "year": "2024", "name": "Eniola Shokunbi", "slug": "eniola-shokunbi"},
  {"profile": 141, "year": "1925", "name": "George Washington Carver", "slug": "george-washington-carver"},
  {"profile": 142, "year": "1940", "name": "Charles R. Drew", "slug": "charles-r-drew"},
  {"profile": 143, "year": "1971", "name": "Robert E. Shurney", "slug": "robert-e-shurney"},
  {"profile": 144, "year": "1975", "name": "Virgie M. Ammons", "slug": "virgie-m-ammons"},
  {"profile": 145, "year": "1982", "name": "Marc Regis Hannah", "slug": "marc-regis-hannah"},
  {"profile": 146, "year": "1987", "name": "Ruane Sharon Jeter", "slug": "ruane-sharon-jeter"},
  {"profile": 147, "year": "1993", "name": "Joanna Hardin", "slug": "joanna-hardin"},
  {"profile": 148, "year": "1997", "name": "Sheila Lynn Jeter", "slug": "sheila-lynn-jeter"},
  {"profile": 149, "year": "2002", "name": "LaTanya Sweeney", "slug": "latanya-sweeney"},
  {"profile": 150, "year": "2009", "name": "Stephanie Luster-Teasley", "slug": "stephanie-luster-teasley"},
  {"profile": 151, "year": "2013", "name": "Jewel Burks Solomon", "slug": "jewel-burks-solomon"},
  {"profile": 152, "year": "2014", "name": "Nashlie H. Sephus", "slug": "nashlie-h-sephus"},
  {"profile": 153, "year": "2015", "name": "Stephanie Lampkin", "slug": "stephanie-lampkin"},
  {"profile": 154, "year": "2015", "name": "Madison Maxey", "slug": "madison-maxey"},
  {"profile": 155, "year": "2016", "name": "Joy Buolamwini", "slug": "joy-buolamwini"},
  {"profile": 156, "year": "2016", "name": "Sevetri Wilson", "slug": "sevetri-wilson"},
  {"profile": 157, "year": "2017", "name": "Dawn Dickson", "slug": "dawn-dickson"},
  {"profile": 158, "year": "2017", "name": "Jasmine Crowe-Houston", "slug": "jasmine-crowe-houston"},
  {"profile": 159, "year": "2019", "name": "Karmella A. Haynes", "slug": "karmella-a-haynes"},
  {"profile": 160, "year": "2020", "name": "Aisha Bowe", "slug": "aisha-bowe"},
  {"profile": 161, "year": "1943", "name": "Henrietta Bradberry", "slug": "henrietta-bradberry"},
  {"profile": 162, "year": "1946", "name": "Jessie T. Pope", "slug": "jessie-t-pope"},
  {"profile": 163, "year": "1951", "name": "Jane C. Wright", "slug": "jane-c-wright"},
  {"profile": 164, "year": "1958", "name": "Mary W. Jackson", "slug": "mary-w-jackson"},
  {"profile": 165, "year": "1961", "name": "Katherine Johnson", "slug": "katherine-johnson"},
  {"profile": 166, "year": "1961", "name": "Dorothy Vaughan", "slug": "dorothy-vaughan"},
  {"profile": 167, "year": "1978", "name": "Debrilla M. Ratchford", "slug": "debrilla-m-ratchford"},
  {"profile": 168, "year": "1990s", "name": "Nola M. Hylton", "slug": "nola-m-hylton"},
  {"profile": 169, "year": "1997", "name": "Dawn J. Wright", "slug": "dawn-j-wright"},
  {"profile": 170, "year": "2005", "name": "Carol Espy-Wilson", "slug": "carol-espy-wilson"},
  {"profile": 171, "year": "2007", "name": "Denise Gray", "slug": "denise-gray"},
  {"profile": 172, "year": "2011", "name": "Kristala L. J. Prather", "slug": "kristala-l-j-prather"},
  {"profile": 173, "year": "2011", "name": "Shelley O'Donnell", "slug": "shelley-o-donnell"},
  {"profile": 174, "year": "2015", "name": "Gwen Jimmere", "slug": "gwen-jimmere"},
  {"profile": 175, "year": "2016", "name": "Ceata E. Lash", "slug": "ceata-e-lash"},
  {"profile": 176, "year": "2017", "name": "Brittany Young", "slug": "brittany-young"},
  {"profile": 177, "year": "2017", "name": "LaShanda Korley", "slug": "lashanda-korley"},
  {"profile": 178, "year": "2017", "name": "Tiera Guinn Fletcher", "slug": "tiera-guinn-fletcher"},
  {"profile": 179, "year": "2018", "name": "Danielle Wood", "slug": "danielle-wood"},
  {"profile": 180, "year": "2020", "name": "Oluwatope “Tope” Fashola Mitchell", "slug": "oluwatope-tope-fashola-mitchell"},
  {"profile": 181, "year": "1896", "name": "Julia T. Hammonds", "slug": "julia-t-hammonds"},
  {"profile": 182, "year": "1907", "name": "Clara C. Frye", "slug": "clara-c-frye"},
  {"profile": 183, "year": "1948", "name": "Portia L. Trenholm", "slug": "portia-l-trenholm"},
  {"profile": 184, "year": "1950", "name": "Lydia M. Holmes", "slug": "lydia-m-holmes"},
  {"profile": 185, "year": "1973", "name": "Gertrude E. Downing", "slug": "gertrude-e-downing"},
  {"profile": 186, "year": "1976", "name": "Evelyn Carmon Nicol", "slug": "evelyn-carmon-nicol"},
  {"profile": 187, "year": "1977", "name": "Beatrice L. Cowans", "slug": "beatrice-l-cowans"},
  {"profile": 188, "year": "1980", "name": "Mildred E. Smith", "slug": "mildred-e-smith"},
  {"profile": 189, "year": "1983", "name": "Maxine W. Snowden", "slug": "maxine-w-snowden"},
  {"profile": 190, "year": "1985", "name": "June B. Horne", "slug": "june-b-horne"},
  {"profile": 191, "year": "1986", "name": "Joan Clark", "slug": "joan-clark"},
  {"profile": 192, "year": "1991", "name": "Tiffany Norwood", "slug": "tiffany-norwood"},
  {"profile": 193, "year": "1992", "name": "Natalie R. Love", "slug": "natalie-r-love"},
  {"profile": 194, "year": "1993", "name": "Brothella Quick", "slug": "brothella-quick"},
  {"profile": 195, "year": "2000", "name": "Deborah Washington Brown", "slug": "deborah-washington-brown"},
  {"profile": 196, "year": "2016", "name": "Sherrill W. Mosee", "slug": "sherrill-w-mosee"},
  {"profile": 197, "year": "2018", "name": "Quintina “Tina” Williams", "slug": "quintina-tina-williams"},
  {"profile": 198, "year": "2021", "name": "Elizabeth P. Clayborne", "slug": "elizabeth-p-clayborne"},
  {"profile": 199, "year": "2023", "name": "Dawn N. Myers", "slug": "dawn-n-myers"},
  {"profile": 200, "year": "2026", "name": "Tekisha L. Lee", "slug": "tekisha-l-lee"},
  {"profile": 201, "year": "1880", "name": "Powell Johnson", "slug": "powell-johnson"},
  {"profile": 202, "year": "1881", "name": "James Wormley", "slug": "james-wormley"},
  {"profile": 203, "year": "1883", "name": "Leonard C. Bailey", "slug": "leonard-c-bailey"},
  {"profile": 204, "year": "1890", "name": "Daniel Johnson", "slug": "daniel-johnson"},
  {"profile": 205, "year": "1891", "name": "William B. Abrams", "slug": "william-b-abrams"},
  {"profile": 206, "year": "1892", "name": "George T. Sampson", "slug": "george-t-sampson"},
  {"profile": 207, "year": "1893", "name": "Thomas W. Stewart", "slug": "thomas-w-stewart"},
  {"profile": 208, "year": "1905", "name": "Robert A. Pelham", "slug": "robert-a-pelham"},
  {"profile": 209, "year": "1943", "name": "Loney Clinton Gordon", "slug": "loney-clinton-gordon"},
  {"profile": 210, "year": "1958", "name": "Marie Maynard Daly", "slug": "marie-maynard-daly"},
];

export const featuredInventors = inventors.filter((inventor) => [1, 2, 3, 4, 5, 7, 15, 17, 50, 51, 56, 60, 61, 148].includes(inventor.profile));

export function getInventor(slug: string) {
  return inventors.find((inventor) => inventor.slug === slug);
}
