import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, FileText, Download } from "lucide-react";
import { BookCover } from "@/components/site/BookCover";
import { InventorCard, PageHero, SectionHeading } from "@/components/site/Editorial";
import { Button } from "@/components/ui/button";
import { featuredInventors } from "@/lib/inventors";
import manuscriptAsset from "@/assets/beyond-the-echoes-manuscript.pdf.asset.json";
import { pageHead } from "@/lib/seo";

const description="Discover the scope, method, and 210 documented profiles in Beyond the Echoes of Black History by James E. Craver.";
export const Route=createFileRoute("/book")({head:()=>({...pageHead("The Book — Beyond the Echoes of Black History",description,"/book"),scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"Book",name:"Beyond the Echoes of Black History",alternateName:"Great Black Inventions",author:{"@type":"Person",name:"James E. Craver"},datePublished:"2026"})}]}),component:BookPage});
function BookPage(){return <>
<PageHero eyebrow="The book" title="A record of invention, struggle, legacy, and impact."><p>Beyond the Echoes of Black History gathers 210 profiles into a chronology spanning 1753 through 2026.</p></PageHero>
<section className="px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1200px] gap-16 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><BookCover className="mx-auto w-full max-w-sm"/><div><SectionHeading eyebrow="About the book" title="Technical achievement within its full historical context."/><div className="mt-7 space-y-5 text-base leading-8 text-muted-foreground"><p>The manuscript documents Black American inventors, innovators, scientists, engineers, and technical contributors across generations.</p><p>Each profile situates a contribution within chronology, evidence, and context. Patent records are distinguished from unpatented work, and popular claims are weighed against the surviving record.</p></div><Button asChild className="mt-8 rounded-none"><Link to="/shop">Purchase the Book <ArrowRight/></Link></Button></div></div></section>
<section className="bg-charcoal px-5 py-20 text-cream lg:px-10 lg:py-28"><div className="mx-auto max-w-[1200px]"><SectionHeading eyebrow="What the book covers" title="A chronology, not a collection of legends." light/><div className="mt-12 grid gap-px bg-cream/15 sm:grid-cols-2 lg:grid-cols-4">{['Invention','Engineering','Scientific achievement','Historical evidence','Persistence','Recognition','Legacy','Impact'].map((x,i)=><div key={x} className="bg-charcoal p-7"><span className="font-display text-3xl text-gold">0{i+1}</span><p className="mt-8 text-xs font-bold uppercase tracking-[.15em]">{x}</p></div>)}</div></div></section>
<section className="px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-[1400px]"><SectionHeading eyebrow="Selected profiles" title="People behind the progress."/><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{featuredInventors.slice(0,4).map(i=><InventorCard inventor={i} key={i.profile}/>)}</div></div></section>
<section className="bg-parchment px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1200px] gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Inside the book" title="Read the opening pages." description="The supplied manuscript includes the complete chronology and individual profiles. Preview the source material directly."/><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="rounded-none"><a href={manuscriptAsset.url} target="_blank" rel="noreferrer"><FileText/>Open Manuscript Preview</a></Button><Button asChild variant="outline" className="rounded-none"><a href={manuscriptAsset.url} download><Download/>Download PDF</a></Button></div></div><div className="paper-grid border border-border bg-card p-8"><p className="eyebrow text-gold">Why this record matters</p><p className="mt-5 font-display text-2xl leading-relaxed">Recognition depends on precision. The manuscript’s historical method protects both the achievement and the truth of the record.</p></div></div></section>
</>}
