import { createFileRoute, Link } from "@tanstack/react-router";
import { LockKeyhole, ArrowLeft } from "lucide-react";
import { BookCover } from "@/components/site/BookCover";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { pageHead } from "@/lib/seo";
export const Route=createFileRoute("/checkout")({validateSearch:(search:Record<string,unknown>)=>({quantity:Math.min(20,Math.max(1,Number(search.quantity)||1))}),head:()=>pageHead("Checkout Preview — James E. Craver","Review the future direct purchase checkout for Beyond the Echoes of Black History.","/checkout"),component:CheckoutPage});
function CheckoutPage(){const {quantity}=Route.useSearch();return <section className="px-5 pb-24 pt-36 lg:px-10 lg:pt-44"><div className="mx-auto max-w-[1200px]"><Link to="/shop" className="inline-flex items-center gap-2 text-xs uppercase tracking-[.14em] text-muted-foreground"><ArrowLeft className="size-3"/>Back to shop</Link><div className="mt-8 grid gap-12 lg:grid-cols-[1.15fr_.85fr]"><div><p className="eyebrow text-gold">Secure checkout preview</p><h1 className="mt-4 font-display text-5xl">Checkout</h1><div className="mt-10 space-y-8"><Fieldset legend="Contact information"><Field label="First Name"/><Field label="Last Name"/><Field label="Email" type="email"/><Field label="Phone" type="tel" optional/></Fieldset><Fieldset legend="Shipping address"><Field label="Country"/><Field label="Address"/><Field label="City"/><Field label="State / Province"/><Field label="Postal Code / ZIP"/></Fieldset><label className="block"><span className="text-sm font-semibold">Order Notes <small className="font-normal text-muted-foreground">(optional)</small></span><textarea className="mt-2 min-h-28 w-full border border-border bg-card p-3 outline-none focus:ring-1 focus:ring-ring"/></label></div><Button disabled className="mt-9 h-12 w-full rounded-none">Payment Unavailable — Setup Pending</Button><p className="mt-4 flex items-center justify-center gap-2 text-xs text-muted-foreground"><LockKeyhole className="size-3"/>No payment details are requested or stored in this preview.</p></div><aside className="h-fit border border-border bg-card p-7 lg:sticky lg:top-24"><h2 className="font-display text-2xl">Order summary</h2><div className="mt-7 flex gap-5 border-b border-border pb-7"><BookCover className="w-24 shrink-0"/><div><p className="font-display text-lg">Beyond the Echoes of Black History</p><p className="mt-2 text-xs text-muted-foreground">Great Black Inventions</p><p className="mt-4 text-sm">Quantity: {quantity}</p></div></div><Summary label="Subtotal" value="Pending"/><Summary label="Shipping" value="Pending"/><Summary label="Total" value="Pending" strong/><div className="mt-7 border-t border-border pt-5 text-xs leading-5 text-muted-foreground"><p>Price, currency, shipping regions, and refund policy must be configured by the author before checkout is activated.</p><p className="mt-3">Future order records route only through the author’s connected cloud project and payment account.</p></div></aside></div></div></section>}
function Fieldset({legend,children}:{legend:string;children:React.ReactNode}){return <fieldset><legend className="font-display text-2xl">{legend}</legend><div className="mt-5 grid gap-5 sm:grid-cols-2">{children}</div></fieldset>}
function Field({label,type='text',optional=false}:{label:string;type?:string;optional?:boolean}){const id=label.toLowerCase().replaceAll(' ','-').replace('/','-');return <label htmlFor={id} className={label==='Address'?'sm:col-span-2':''}><span className="text-sm font-semibold">{label} {optional&&<small className="font-normal text-muted-foreground">(optional)</small>}</span><Input id={id} type={type} disabled className="mt-2 h-11 rounded-none bg-card"/></label>}
function Summary({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className={`flex justify-between border-b border-border py-4 ${strong?'font-display text-xl':''}`}><span>{label}</span><span>{value}</span></div>}
