import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Mail, Send } from "lucide-react";
import { PageHero } from "@/components/site/Editorial";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { pageHead } from "@/lib/seo";
export const Route=createFileRoute("/contact")({head:()=>pageHead("Contact James E. Craver","Contact the author’s team about the book, author, or media and speaking inquiries.","/contact"),component:ContactPage});
function ContactPage(){const [notice,setNotice]=useState(false);return <><PageHero eyebrow="Get in touch" title="Contact"><p>For questions about the book, author inquiries, and media or speaking requests.</p></PageHero><section className="px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1100px] gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><Mail className="text-gold"/><h2 className="mt-5 font-display text-3xl">Correspondence</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">The author’s domain and working contact address have not yet been supplied.</p><p className="mt-6 text-sm">sales@[author-domain].com</p><p className="mt-8 text-xs leading-5 text-muted-foreground">Form delivery remains inactive until an author-owned destination is connected. Messages are not routed to an invented third party.</p></div><form onSubmit={e=>{e.preventDefault();setNotice(true)}} className="grid gap-5 sm:grid-cols-2"><ContactField label="Name"/><ContactField label="Email" type="email"/><ContactField label="Phone" type="tel" optional/><label><span className="text-sm font-semibold">Inquiry category</span><select className="mt-2 h-11 w-full border border-border bg-card px-3"><option>General</option><option>Book</option><option>Author</option><option>Media / speaking</option></select></label><ContactField label="Subject" wide/><label className="sm:col-span-2"><span className="text-sm font-semibold">Message</span><textarea required className="mt-2 min-h-40 w-full border border-border bg-card p-3 outline-none focus:ring-1 focus:ring-ring"/></label><div className="sm:col-span-2"><Button className="h-12 rounded-none" type="submit"><Send/>Check Availability</Button>{notice&&<p role="status" className="mt-4 border-l-2 border-gold pl-4 text-sm text-muted-foreground">Message delivery is not yet connected. Please return when the author’s official address is published.</p>}</div></form></div></section></>}
function ContactField({label,type='text',optional=false,wide=false}:{label:string;type?:string;optional?:boolean;wide?:boolean}){return <label className={wide?'sm:col-span-2':''}><span className="text-sm font-semibold">{label} {optional&&<small className="font-normal text-muted-foreground">(optional)</small>}</span><Input required={!optional} type={type} className="mt-2 h-11 rounded-none bg-card"/></label>}
