import { createFileRoute } from "@tanstack/react-router";
import { Search, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { InventorCard, PageHero } from "@/components/site/Editorial";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { inventors } from "@/lib/inventors";
import { pageHead } from "@/lib/seo";
export const Route=createFileRoute("/inventors")({head:()=>pageHead("The Inventors — Beyond the Echoes", "Search 210 inventor, innovator, scientist, engineer, and technical contributor profiles from James E. Craver’s manuscript.","/inventors"),component:InventorsPage});
function InventorsPage(){const [q,setQ]=useState("");const [era,setEra]=useState("all");const [sort,setSort]=useState("profile");const [shown,setShown]=useState(24);const filtered=useMemo(()=>{const matches=inventors.filter(i=>i.name.toLowerCase().includes(q.toLowerCase())&&(era==='all'||era==='1800s'&&Number.parseInt(i.year)>=1800&&Number.parseInt(i.year)<1900||era==='1900s'&&Number.parseInt(i.year)>=1900&&Number.parseInt(i.year)<2000||era==='2000s'&&Number.parseInt(i.year)>=2000));return [...matches].sort((a,b)=>sort==='alpha'?a.name.localeCompare(b.name):a.profile-b.profile)},[q,era,sort]);return <><PageHero eyebrow="The invention archive" title="The Inventors"><p>Explore the 210 documented profiles presented in <em>Beyond the Echoes of Black History</em>.</p></PageHero><section className="px-5 py-16 lg:px-10 lg:py-24"><div className="mx-auto max-w-[1400px]"><div className="grid gap-3 border-y border-border py-5 md:grid-cols-[1fr_180px_180px]"><label className="relative"><span className="sr-only">Search inventors</span><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="h-12 rounded-none border-border bg-card pl-10" value={q} onChange={e=>{setQ(e.target.value);setShown(24)}} placeholder="Search by inventor name"/></label><label><span className="sr-only">Filter by era</span><select className="h-12 w-full border border-border bg-card px-3 text-sm" value={era} onChange={e=>{setEra(e.target.value);setShown(24)}}><option value="all">All years</option><option value="1800s">1800s</option><option value="1900s">1900s</option><option value="2000s">2000s</option></select></label><label><span className="sr-only">Sort profiles</span><select className="h-12 w-full border border-border bg-card px-3 text-sm" value={sort} onChange={e=>setSort(e.target.value)}><option value="profile">Manuscript order</option><option value="alpha">Alphabetical</option></select></label></div><div className="mt-7 flex items-center justify-between"><p className="text-sm text-muted-foreground"><strong className="text-foreground">{filtered.length}</strong> profiles</p><p className="flex items-center gap-2 text-xs uppercase tracking-[.12em] text-muted-foreground"><SlidersHorizontal className="size-3"/>Data drawn from manuscript index</p></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.slice(0,shown).map(i=><InventorCard key={i.profile} inventor={i}/>)}</div>{shown<filtered.length&&<div className="mt-12 text-center"><Button variant="outline" className="h-12 rounded-none px-8" onClick={()=>setShown(v=>v+24)}>Load More Profiles</Button></div>}{filtered.length===0&&<div className="py-24 text-center"><p className="font-display text-3xl">No matching profiles</p><p className="mt-3 text-muted-foreground">Try a different name or era.</p></div>}</div></section></>}
