import { createFileRoute, Link } from "@tanstack/react-router";
import { Minus, Plus, ShieldCheck, Truck, RotateCcw, ArrowRight } from "lucide-react";
import { useState, type ReactNode } from "react";
import { BookCover } from "@/components/site/BookCover";
import { PageHero } from "@/components/site/Editorial";
import { Button } from "@/components/ui/button";
import { pageHead } from "@/lib/seo";
export const Route=createFileRoute("/shop")({head:()=>({...pageHead("Shop — Beyond the Echoes of Black History","Purchase Beyond the Echoes of Black History: Great Black Inventions directly from James E. Craver.","/shop"),scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"Product",name:"Beyond the Echoes of Black History",brand:{"@type":"Person",name:"James E. Craver"},description:"Great Black Inventions"})}]}),component:ShopPage});
function ShopPage(){const [quantity,setQuantity]=useState(1);return <><PageHero eyebrow="The official book shop" title="Bring the history home."><p>Purchase <em>Beyond the Echoes of Black History: Great Black Inventions</em> directly from the author’s storefront.</p></PageHero><section className="px-5 py-20 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[1200px] gap-16 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><BookCover className="mx-auto w-full max-w-sm"/><div><p className="eyebrow text-gold">James E. Craver</p><h1 className="mt-4 font-display text-4xl leading-tight sm:text-5xl">Beyond the Echoes of Black History</h1><p className="mt-2 font-display text-xl italic text-bronze">Great Black Inventions</p><p className="mt-6 max-w-2xl leading-7 text-muted-foreground">A historical record of Black American innovation, invention, scientific achievement, engineering, and perseverance across generations.</p><div className="mt-8 border-y border-border py-6"><p className="eyebrow text-muted-foreground">Price</p><p className="mt-2 font-display text-3xl">Price forthcoming</p><p className="mt-2 text-sm text-muted-foreground">Retail price and currency have not yet been supplied.</p></div><div className="mt-7"><label className="eyebrow text-muted-foreground" htmlFor="quantity">Quantity</label><div className="mt-3 flex w-36 items-center border border-border bg-card"><button className="grid size-11 place-items-center" onClick={()=>setQuantity(q=>Math.max(1,q-1))} aria-label="Decrease quantity"><Minus className="size-4"/></button><span id="quantity" className="flex-1 text-center font-semibold">{quantity}</span><button className="grid size-11 place-items-center" onClick={()=>setQuantity(q=>Math.min(20,q+1))} aria-label="Increase quantity"><Plus className="size-4"/></button></div></div><div className="mt-7 flex flex-wrap gap-3"><Button disabled className="h-12 rounded-none px-8">Add to Cart</Button><Button asChild variant="outline" className="h-12 rounded-none px-8"><Link to="/checkout" search={{quantity}}>Preview Checkout <ArrowRight/></Link></Button></div><p className="mt-4 max-w-xl text-xs leading-5 text-muted-foreground">Ordering remains inactive until the author supplies retail price, currency, shipping terms, policies, and a payment-provider account. No payment will be collected.</p></div></div></section><section className="bg-charcoal px-5 py-16 text-cream lg:px-10"><div className="mx-auto grid max-w-[1200px] gap-8 sm:grid-cols-3"><Trust icon={<ShieldCheck/>} title="Secure architecture" text="Ready for an author-owned payment account; no credentials invented."/><Trust icon={<Truck/>} title="Shipping" text="Rates and service regions forthcoming from the author."/><Trust icon={<RotateCcw/>} title="Returns" text="Refund and return policy awaiting author approval."/></div></section></>}
function Trust({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="border-l border-gold pl-5"><div className="text-gold">{icon}</div><h2 className="mt-4 font-display text-xl">{title}</h2><p className="mt-2 text-sm leading-6 text-cream/55">{text}</p></div>}
