/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as BookRouteImport } from './routes/book'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InventorsRouteImport } from './routes/inventors'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as InventorsSlugRouteImport } from './routes/inventors.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorsRoute = InventorsRouteImport.update({
  id: '/inventors',
  path: '/inventors',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorsSlugRoute = InventorsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InventorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/author': typeof AuthorRoute
  '/book': typeof BookRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/inventors': typeof InventorsRouteWithChildren
  '/shop': typeof ShopRoute
  '/timeline': typeof TimelineRoute
  '/inventors/$slug': typeof InventorsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/author': typeof AuthorRoute
  '/book': typeof BookRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/inventors': typeof InventorsRouteWithChildren
  '/shop': typeof ShopRoute
  '/timeline': typeof TimelineRoute
  '/inventors/$slug': typeof InventorsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/author': typeof AuthorRoute
  '/book': typeof BookRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/inventors': typeof InventorsRouteWithChildren
  '/shop': typeof ShopRoute
  '/timeline': typeof TimelineRoute
  '/inventors/$slug': typeof InventorsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/author'
    | '/book'
    | '/checkout'
    | '/contact'
    | '/inventors'
    | '/shop'
    | '/timeline'
    | '/inventors/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/author'
    | '/book'
    | '/checkout'
    | '/contact'
    | '/inventors'
    | '/shop'
    | '/timeline'
    | '/inventors/$slug'
  id:
    | '__root__'
    | '/'
    | '/author'
    | '/book'
    | '/checkout'
    | '/contact'
    | '/inventors'
    | '/shop'
    | '/timeline'
    | '/inventors/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorRoute: typeof AuthorRoute
  BookRoute: typeof BookRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  InventorsRoute: typeof InventorsRouteWithChildren
  ShopRoute: typeof ShopRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventors': {
      id: '/inventors'
      path: '/inventors'
      fullPath: '/inventors'
      preLoaderRoute: typeof InventorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventors/$slug': {
      id: '/inventors/$slug'
      path: '/$slug'
      fullPath: '/inventors/$slug'
      preLoaderRoute: typeof InventorsSlugRouteImport
      parentRoute: typeof InventorsRoute
    }
  }
}

interface InventorsRouteChildren {
  InventorsSlugRoute: typeof InventorsSlugRoute
}

const InventorsRouteChildren: InventorsRouteChildren = {
  InventorsSlugRoute: InventorsSlugRoute,
}

const InventorsRouteWithChildren = InventorsRoute._addFileChildren(
  InventorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorRoute: AuthorRoute,
  BookRoute: BookRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  InventorsRoute: InventorsRouteWithChildren,
  ShopRoute: ShopRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
